name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  # Uso de la máquina completa

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the application
      run: ./build.sh

